let data = [
    {
        "images": "https://raw.githubusercontent.com/Migueg04/PaginaWeb/main/Imagenes/dichotomy.jpg" ,
        "albumName": "Dichotomy",
        "artist": "David Kushner-2024",
        "price": "$40.99",
        "discount": "10% OFF",
        "label": "Virgin Music",
        "format": "2LP Vinyl",
        "colour" : "Black Vinyl",
        "genre": "Pop",
        "style": "Ballad",
        "year": "2024",
        
        "songs" : [
            "No High",
            "Poison",
            "Skin and Bones",
            "Hero",
            "You and Me",
            "Love Is Going To Kill Us", 
            "Dead Man",
            "Flesh x Blood",
            "Sweet Oblivion",
            "Buried at Sea",
        ],
        "songs2" : [
            "Humankind",
            "Universe",
            "Heaven Sees",
            "Darkerside",
            "California Nights",
            "Saving Your Soul",
            "Daylight",
        ]
      
    },
    {
        "images": "https://raw.githubusercontent.com/Migueg04/PaginaWeb/main/Imagenes/queen.jpg",
        "albumName": "A Night at the Opera",
        "artist": "Queen-1975",
        "price": "$35.99",
        "discount": "25% OFF",
        "label": "Commercial Marketing",
        "format": "LP Vinyl",
        "colour" : "Black Vinyl",
        "genre": "Rock",
        "style": "Hard Rock, Pop Rock, Classic Rock",
        "year": "1975",
        "songs" : [
            "Death On Two Legs",
            "Lazing On A Sunday Afternoon",
            "I'm In Love With My Car",
            "You're My Best Friend",
            "39",
            "Sweet Lady",
        ],
        "songs2" : [
            "Seaside Rendezvous",
            "The Prophet's Song",
            "Love Of My Life",
            "Good Company",
            "Bohemian Rhapsody",
            "God Save The Queen"
        ]

    },
    {
        "images": "https://raw.githubusercontent.com/Migueg04/PaginaWeb/main/Imagenes/Bon%20Jovi.jpg",
        "albumName": "Bon Jovi's Greatest Hits",
        "artist": "Bon Jovi-various years",
        "price": "$60.99",
        "discount": "30% OFF",
        "label": "Commercial Marketing",
        "format": "2LP Vinyl",
        "colour" : "Black Vinyl",
        "genre": "Rock",
        "style": "Arena Rock, Glam, Hard Rock, Pop Rock",
        "year": "2024",
        "songs" : [
            "Livin' On A Prayer",
            "You Give Love A Bad Name",
            "It's My Life",
            "Have A Nice Day",
            "Wanted Dead Or Alive",
            "Bad Medicine", 
            "We Weren't Born To Follow",
            "I'll Be There For You",
        ],
        "songs2" : [
            "Born To Be My Baby",
            "Blaze Of Glory",
            "Who Says You Can't Go Homed",
            "Lay Your Hands On Me",
            "Always",
            "Runaway",
            "What Do You Got?",
            "No Apologies",
        ]
            
        
    },
    {
        "images": "https://raw.githubusercontent.com/Migueg04/PaginaWeb/main/Imagenes/Free.jpg",
        "albumName": "FREE",
        "artist": "Rick Astley-1991",
        "price": "$30.99",
        "discount": "",
        "label": "BMG Rights Management",
        "format": "LP Vinyl",
        "colour" : "Black Vinyl",
        "genre": "Pop",
        "style": "Synth-pop, Ballad, Vocal",
        "year": "1991",
        "songs" : [
            "In The Name Of Love",
            "Cry For Help",
            "Move Right Out",
            "Be With You",
            "Really Got A Problem",
            "Is This Really Love",
        ],
        "songs2" : [
            "This Must Be Heaven",
            "Never Knew Love",
            "The Bottom Line",
            "Wonderful You",
            "Behind The Smile",
        ]
            
    },
    {
        "images": "https://raw.githubusercontent.com/Migueg04/PaginaWeb/main/Imagenes/Solos.jpg",
        "albumName": "SOLOS",
        "artist": "Bryce Dessner-2023",
        "price": "$40.99",
        "discount": "",
        "label": "Masterworks",
        "format": "2LP Vinyl",
        "colour" : "Black Vinyl",
        "genre": "Classical",
        "style": "Contemporary",
        "year": "2023",
        "songs" : [
            "Lullaby for Jacques et Brune",
            "Francis",
            "Tuusula",
            "Song for Octave",
            "Tromp Miniature",
            "Ornament and Crime I", 
            "Ornament and Crime II",
            "Ornament and Crime III",
        ],
        "songs2" : [
            "A Good Person",
            "On a Wire",
            "Walls",
            "Delphica I",
            "Delphica II",
            "Ornament III Piano",
            "Song for Ainola",
        ]
    },
    {
        "images": "https://raw.githubusercontent.com/Migueg04/PaginaWeb/main/Imagenes/Sabrina.jpg",
        "albumName": "Short n' Sweet - Blue Edition",
        "artist": "Sabrina Carpenter-2024",
        "price": "$45.99",
        "discount": "",
        "label": "Commercial Marketing",
        "format": "LP Vinyl",
        "colour" : "Baby Blue Vinyl",
        "genre": "Pop",
        "style": "Country, Dance-pop",
        "year": "2024",
        "songs" :[
            "Taste",
            "Please Please Please",
            "Good Graces",
            "Sharpest Tool",
            "Coincidence",
            "Bed Chem",
        ],
        "songs2" : [
            "Espresso",
            "Dumb & Poetic",
            "Slim Pickins",
            "Juno",
            "Lie To Girls",
            "Don't Smile",
        ]
            
    },
    {
        "images": "https://raw.githubusercontent.com/Migueg04/PaginaWeb/main/Imagenes/mufasa.jpg",
        "albumName": "THE LION KING - ZOETROPE",
        "artist": "Various-1993",
        "price": "$70.99",
        "discount": "10% OFF",
        "label": "UMR",
        "format": "LP Vinyl",
        "colour" : "Zoetrope Vinyl",
        "genre": "Stage & Screen",
        "style": "Soundtrack",
        "year": "1993",
        "songs" :[
            "Circle of Life",
            "I Just Can't Wait to Be King",
            "Be Prepared",
            "Hakuna Matata",
            "Can You Feel the Love Tonight",
            "This Land",
        ],
        "songs2" : [
            "...To Die For",
            "Under the Stars",
            "King of Pride Rock",
            "Circle of Life",
            "I Just Can't Wait to Be King - Performed by Elton John",
            "Can You Feel the Love Tonight - Performed by Elton John",
        ]
            
    },
    {
        "images": "https://raw.githubusercontent.com/Migueg04/PaginaWeb/main/Imagenes/mermaid.jpg",
        "albumName": "The Little Mermaid",
        "artist": "Various-1996",
        "price": "$40.99",
        "discount": "10% OFF",
        "label": "UMR",
        "format": "LP Vinyl",
        "colour" : "Transparent Splatter Vinyl",
        "genre": "Stage & Screen",
        "style": "Score, Musical",
        "year": "1989",
        "songs" : [
            "Fathoms Below",
            "Main Titles",
            "Fanfare",
            "Daughters of Triton",
            "Part of Your World",
            "Under the Sea", 
            "Part of Your World (Reprise)",
            "Poor Unfortunate Souls",
            "Les Poissons",
            "Kiss the Girl",
        ],
        "songs2" : [
            "Fireworks",
            "Jig",
            "The Storm",
            "Destruction of the Grotto",
            "Flotsam and Jetsam",
            "Tour of the Kingdom",
            "Bedtime",
            "Wedding Announcement",
            "Eric to the Rescue",
            "Happy Ending",
        ]
    },
    {
        "images": "https://raw.githubusercontent.com/Migueg04/PaginaWeb/main/Imagenes/Jimi.jpg",
        "albumName": "Electric Ladyland",
        "artist": "Jimi Hendrix-1968",
        "price": "$38.99",
        "discount": "25% OFF",
        "label": "Sony Music CMG",
        "format": "2LP Vinyl",
        "colour" : "Black Vinyl",
        "genre": "Rock",
        "style": "Blues Rock, Psychedelic Rock",
        "year": "2010",
        "songs" :[
            "...And the Gods Made Love",
            "Have You Ever Been (To Electric Ladyland)",
            "Crosstown Traffic",
            "Voodoo Chile",
            "Little Miss Strange",
            "Long Hot Summer Night", 
            "Come On (Part 1)",
            "Gypsy Eyes",
        ],
        "songs2" : [
            "Burning of the Midnight Lamp",
            "Rainy Day, Dream Away",
            "1983... (A Merman I Should Turn To Be)",
            "Moon, Turn The Tides... Gently Away",
            "Still Dreaming, Still Raining",
            "House Burning Down",
            "All Along the Watchtower",
            "Voodoo Child (Slight Return)",
        ]   
    },
    {
        "images": "https://raw.githubusercontent.com/Migueg04/PaginaWeb/main/Imagenes/beatles.jpg",
        "albumName": "Let It Be",
        "artist": "The Beatles-1970",
        "price": "$35.99",
        "discount": "40% OFF",
        "label": "Masterworks",
        "format": "LP Vinyl",
        "colour" : "Black Vinyl",
        "genre": "Rock",
        "style": "Pop Rock",
        "year": "1970",
        "songs" : [
            "One After 909",
            "Rocker",
            "Save the Last Dance for Me",
            "Don't Let Me Down",
            "Dig a Pony",
            "I've Got a Feeling", 
            "Get Back",
            "For You Blue",
        ],
        "songs2" : [
            "Teddy Boy",
            "Two of Us",
            "Maggie Mae",
            "Dig It",
            "Let It Be",
            "The Long and Winding Road",
            "Get Back (reprise)",
        ]
            
    },
    {
        "images": "https://raw.githubusercontent.com/Migueg04/PaginaWeb/main/Imagenes/kiss.jpg",
        "albumName": "Creatures of the Night",
        "artist": "KISS-1981",
        "price": "$34.99",
        "discount": "20% OFF",
        "label": "UMC",
        "format": "LP Vinyl",
        "colour" : "Black Vinyl",
        "genre": "Rock",
        "style": "Hard Rock, Heavy Metal",
        "year": "1982",
        "songs" : [
            "Creatures Of  The Night",
            "Keep Me Comin'",
            "Saint and Sinner",
            "Rock And Roll Hell",
            "Danger",
        ],
        "songs2" : [
            "I Love It Loud", 
            "I Still Love You",
            "Killer",
            "War Machine",
        ]
            
    },
    {
        "images": "https://raw.githubusercontent.com/Migueg04/PaginaWeb/main/Imagenes/acdc.jpg",
        "albumName": "The Razor's Edge",
        "artist": "ACDC-1990",
        "price": "$32.99",
        "discount": "19% OFF",
        "label": "Sony Music CMG",
        "format": "LP Vinyl",
        "colour" : "Gold Vinyl",
        "genre": "Rock",
        "style": "Hard Rock",
        "year": "1990",
        "songs" : [
            "Thunderstruck",
            "Fire Your Guns",
            "Moneytalks",
            "The Razors Edge",
            "Mistress For Christmas",
            "Rock Your Heart Out",
        ],
        "songs2" : [
            "Are You Ready",
            "Got You By The Balls",
            "Shot Of Love",
            "Let's Make It",
            "Good Bye And Good Riddance To Bad Luck",
            "If you Dare",
        ]

    },
    {
        "images": "https://www.therecordhub.com/cdn/shop/files/AnEveningWithSilkSonic_ExtraTracks_800x.png?v=1690092323",
        "albumName": "An Evening With Silk Sonic",
        "artist": "Bruno Mars & Anderson Paak-2021",
        "price": "$29.99",
        "discount": "",
        "label": "Atlantic",
        "format": "LP Vinyl",
        "colour" : "Black Vinyl",
        "genre": "Soul",
        "style": "	Contemporary R&B, Soul",
        "year": "2021",
        "songs" :[
            "Silk Sonic Intro",
            "Leave the Door Open",
            "Fly As Me",
            "After Last Night",
            "Smoke Out the Window",
        ],
        "songs2" : [
            " Put On a Smile",
            "777",
            "Skate",
            "Blast Off",
            "Love's Train (Bonus Track) ",
        ]      
    },
    {
        "images": "https://www.therecordhub.com/cdn/shop/products/dualipablacklp_800x.png?v=1594948506",
        "albumName": "Future Nostalgia",
        "artist": "Dua Lipa-2020",
        "price": "$35.99",
        "discount": "",
        "label": "Warner Bros Records",
        "format": "LP Vinyl",
        "colour" : "Black Vinyl",
        "genre": "Pop",
        "style": "Power Pop, Dance-pop, Funk",
        "year": "2020",
        "songs" : [
            "Future Nostalgia",
            "Don’t Start Now",
            "Cool",
            "Physical",
            "Levitating",
            "Pretty Please", 
            
            
            
        ],
        "songs2" : [
            "Hallucinate",
            "Love Again",
            "Break My Heart",
            "Good In Bed [Explicit]",
            "Boys Will Be Boys",
        ]           
    },
    {
        "images": "https://www.therecordhub.com/cdn/shop/products/LALALAND_800x.png?v=1610125048",
        "albumName": "La La Land",
        "artist": "Various-2016",
        "price": "$40.99",
        "discount": "",
        "label": "Interscope",
        "format": "LP Vinyl",
        "colour" : "Black Vinyl",
        "genre": "Stage & Screen",
        "style": "Soundtrack, Musical, Score",
        "year": "2017",
        "songs" : [
            "Another Day Of Sun",
            "Someone In The Crowd",
            "Mia & Sebastian's Theme",
            "A Lovely Night",
            "Herman's Habit",
            "City Of Stars", 
            "Planetarium",
            "Summer Montage / Madeline",
        ],
        "songs2" : [
            
            "City Of Stars",
            "Start A Fire",
            "Engagement Party",
            "Audition (The Fools Who Dream)",
            "Epilogue",
            "The End",
            "City Of Stars (Humming)"
        ]
    },
    
]